version: '3'
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.16.18.0/24"  # 需根据实际网络环境规划
services:
  etcd-01:
    restart: always
    image: konomo/etcd/etcd:v1
    container_name: etcd-01
    environment:
      - NAME=etcd-01
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-01:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-01:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2379:2379"
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcd-02:
    restart: always
    image: konomo/etcd/etcd:v1
    container_name: etcd-02
    environment:
      - NAME=etcd-02
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-02:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-02:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcd-03:
    restart: always
    image: konomo/etcd/etcd:v1
    container_name: etcd-03
    environment:
      - NAME=etcd-03
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-03:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-03:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcdkeeper:
    restart: always
    image: konomo/etcd/etcdkeeper:v1
    environment:
      - ETCDKEEPER_USETLS=true
      - ETCDKEEPER_CACERT=etcd-ca.pem 
      - ETCDKEEPER_CERT=kube-etcd-healthcheck-client.pem
      - ETCDKEEPER_KEY=kube-etcd-healthcheck-client-key.pem
      - ETCDKEEPER_PORT=8080
    container_name: etcdkeeper
    ports:
      - "8080:8080"
    volumes:
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  kube-apiserver:
    # restart: always
    image: konomo/k8s/kube-apiserver:v1
    environment:
      - BIND_ADDRESS=0.0.0.0
      - ADVERTISE_ADDRESS=0.0.0.0
      - SECURE_PORT=6443
      - SERVICE_CLUSTER_IP_RANGE=10.1.0.0/16
      - ETCD_SERVERS=https://etcd-01:2379
      - TOKEN_AUTH_FILE=bootstrap-token.csv
      - ETCD_CAFILE=etcd-ca.pem
      - ETCD_CERTFILE=kube-apiserver-etcd-client.pem
      - ETCD_KEYFILE=kube-apiserver-etcd-client-key.pem
      - CLIENT_CA_FILE=k8s-ca.pem
      - SERVICE_ACCOUNT_KEY_FILE=k8s-ca-key.pem
      - SERVICE_ACCOUNT_SIGNING_KEY_FILE=k8s-ca-key.pem
      - SERVICE_ACCOUNT_ISSUER=api
      - TLS_CERT_FILE=kube-apiserver.pem
      - TLS_PRIVATE_KEY_FILE=kube-apiserver-key.pem
      - KUBELET_CLIENT_CERTIFICATE=kube-apiserver-client.pem
      - KUBELET_CLIENT_KEY=kube-apiserver-client-key.pem
      - REQUESTHEADER_CLIENT_CA_FILE=k8s-front-proxy-ca.pem
      - PROXY_CLIENT_CERT_FILE=front-proxy-client.pem
      - PROXY_CLIENT_KEY_FILE=front-proxy-client-key.pem
    container_name: kube-apiserver
    ports:
      - "6443:6443"
    volumes:
      - ${etcd_pki_dir}:/root/pki/etcd
      - ${k8s_pki_dir}:/root/pki/k8s
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/kube-apiserver_entrypoint.sh
