version: '3'
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.18.0/24"  # 需根据实际网络环境规划
services:
  etcd-01:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/etcd:v1
    container_name: etcd-01
    environment:
      - NAME=etcd-01
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-01:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-01:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcd-02:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/etcd:v1
    container_name: etcd-02
    environment:
      - NAME=etcd-02
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-02:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-02:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcd-03:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/etcd:v1
    container_name: etcd-03
    environment:
      - NAME=etcd-03
      - DATA_DIR=/data/etcd
      - LISTEN_PEER_URLS=https://0.0.0.0:2380
      - LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
      - INITIAL_ADVERTISE_PEER_URLS=https://etcd-03:2380
      - INITIAL_CLUSTER=etcd-01=https://etcd-01:2380,etcd-02=https://etcd-02:2380,etcd-03=https://etcd-03:2380
      - INITIAL_CLUSTER_TOKEN=etcd-cluster
      - INITIAL_CLUSTER_STATE=new
      - CLIENT_AUTO_TLS=false
      - CLIENT_CLIENT_CERT_AUTH=true
      - CLIENT_CERT_FILE=/root/pki/etcd-client.pem
      - CLIENT_KEY_FILE=/root/pki/etcd-client-key.pem
      - CLIENT_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - PEER_AUTO_TLS=false
      - PEER_CLIENT_CERT_AUTH=true
      - PEER_CERT_FILE=/root/pki/etcd-peer.pem
      - PEER_KEY_FILE=/root/pki/etcd-peer-key.pem
      - PEER_TRUSTED_CA_FILE=/root/pki/etcd-ca.pem
      - ENABLE_PPROF=true
      - LOG_LEVEL=debug
      - LOGGER=zap
      - LOG_OUTPUTS=[stderr]
    volumes:
      - ${data_dir}/etcd-03:/data/etcd
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    entrypoint:
      - /root/entrypoint.sh

  etcdkeeper:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/etcdkeeper:v1
    environment:
      - ETCDKEEPER_USETLS=true
      - ETCDKEEPER_CACERT=etcd-ca.pem 
      - ETCDKEEPER_CERT=kube-etcd-healthcheck-client.pem
      - ETCDKEEPER_KEY=kube-etcd-healthcheck-client-key.pem
      - ETCDKEEPER_PORT=8080
    container_name: etcdkeeper
    ports:
      - "8080:8080"
    volumes:
      - ${etcd_pki_dir}:/root/pki
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    depends_on:
      - etcd-01
      - etcd-02
      - etcd-03
    entrypoint:
      - /root/entrypoint.sh

  kube-apiserver:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/kube-apiserver:v1.24.1
    # environment:
    #   - K8S_PKI_DIR=/root/pki/k8s
    #   - ETCD_PKI_DIR=/root/pki/etcd
    container_name: kube-apiserver
    ports:
      - "6443:6443"
    volumes:
      - ${etcd_pki_dir}:/root/pki/etcd
      - ${k8s_pki_dir}:/root/pki/k8s
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynet
    depends_on:
      - etcd-01
      - etcd-02
      - etcd-03
    entrypoint:
      - /root/wait-for-it.sh
      - -t
      - '0'
      - etcd-01:2379
      - --
      - /root/kube-apiserver
      - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction
      - --allow-privileged=true
      - --v=2 
      - --service-node-port-range=1-65500 
      - --authorization-mode=Node,RBAC 
      - --anonymous-auth=false 
      - --enable-bootstrap-token-auth 
      - --bind-address=0.0.0.0
      - --advertise-address=0.0.0.0
      - --secure-port=6443
      - --service-cluster-ip-range=10.1.0.0/16
      - --token-auth-file=/root/pki/k8s/bootstrap-token.csv
      - --etcd-servers=https://etcd-01:2379,https://etcd-02:2379,https://etcd-03:2379
      - --etcd-cafile=/root/pki/etcd/etcd-ca.pem
      - --etcd-certfile=/root/pki/etcd/kube-apiserver-etcd-client.pem
      - --etcd-keyfile=/root/pki/etcd/kube-apiserver-etcd-client-key.pem
      - --client-ca-file=/root/pki/k8s/k8s-ca.pem
      - --service-account-key-file=/root/pki/k8s/k8s-ca-key.pem
      - --service-account-signing-key-file=/root/pki/k8s/k8s-ca-key.pem
      - --service-account-issuer=api
      - --tls-cert-file=/root/pki/k8s/kube-apiserver.pem
      - --tls-private-key-file=/root/pki/k8s/kube-apiserver-key.pem
      - --kubelet-client-certificate=/root/pki/k8s/kube-apiserver-kubelet-client.pem
      - --kubelet-client-key=/root/pki/k8s/kube-apiserver-kubelet-client-key.pem
      - --requestheader-client-ca-file=/root/pki/k8s/k8s-front-proxy-ca.pem
      - --proxy-client-cert-file=/root/pki/k8s/front-proxy-client.pem
      - --proxy-client-key-file=/root/pki/k8s/front-proxy-client-key.pem

  kube-controller-manager:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/kube-controller-manager:v1.24.1
    # environment:
    #   - K8S_PKI_DIR=/root/pki/k8s
    container_name: kube-controller-manager
    volumes:
      - ${k8s_pki_dir}:/root/pki/k8s
      - /etc/localtime:/etc/localtime:ro
    network_mode: "service:kube-apiserver"
    depends_on:
      - kube-apiserver
    entrypoint:
      - /root/wait-for-it.sh
      - -t
      - '0'
      - kube-apiserver:6443
      - --
      - /root/kube-controller-manager
      - --leader-elect=true
      - --v=2
      - --cluster-signing-duration=876000h
      - --use-service-account-credentials
      - --controllers=*,bootstrapsigner,tokencleaner
      # - --requestheader-allowed-names=""
      - --requestheader-extra-headers-prefix="X-Remote-Extra-"
      - --requestheader-group-headers=X-Remote-Group
      - --requestheader-username-headers=X-Remote-User
      - --cluster-name=kubernetes
      - --bind-address=0.0.0.0
      - --secure-port=10257
      - --master=https://kube-apiserver:6443
      - --service-cluster-ip-range=10.1.0.0/16
      - --cluster-cidr=10.1.0.0/16
      - --requestheader-client-ca-file=/root/pki/k8s/k8s-ca.pem
      - --client-ca-file=/root/pki/k8s/k8s-ca.pem
      - --cluster-signing-cert-file=/root/pki/k8s/k8s-ca.pem
      - --cluster-signing-key-file=/root/pki/k8s/k8s-ca-key.pem
      - --tls-cert-file=/root/pki/k8s/kube-controller-manager.pem
      - --tls-private-key-file=/root/pki/k8s/kube-controller-manager-key.pem
      - --root-ca-file=/root/pki/k8s/k8s-ca.pem
      - --service-account-private-key-file=/root/pki/k8s/k8s-ca-key.pem
      - --authentication-kubeconfig=/root/pki/k8s/kube-controller-manager.kubeconfig
      - --authorization-kubeconfig=/root/pki/k8s/kube-controller-manager.kubeconfig
      - --kubeconfig=/root/pki/k8s/kube-controller-manager.kubeconfig

  kube-scheduler:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/wenxl/kube-scheduler:v1.24.1
    # environment:
    #   - K8S_PKI_DIR=/root/pki/k8s
    container_name: kube-scheduler
    volumes:
      - ${k8s_pki_dir}:/root/pki/k8s
      - /etc/localtime:/etc/localtime:ro
    network_mode: "service:kube-apiserver"
    depends_on:
      - kube-apiserver
    entrypoint:
      - /root/wait-for-it.sh
      - -t
      - '0'
      - kube-apiserver:6443
      - --
      - /root/kube-scheduler
      - --v=2
      - --leader-elect=true
      - --bind-address=0.0.0.0
      - --secure-port=10259
      - --master=https://kube-apiserver:6443
      - --tls-cert-file=/root/pki/k8s/kube-scheduler.pem
      - --tls-private-key-file=/root/pki/k8s/kube-scheduler-key.pem
      - --authentication-kubeconfig=/root/pki/k8s/kube-scheduler.kubeconfig
      - --authorization-kubeconfig=/root/pki/k8s/kube-scheduler.kubeconfig
      - --kubeconfig=/root/pki/k8s/kube-scheduler.kubeconfig
