version: '3'
networks:
  # base-network:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "172.16.10.0/24"  # 需根据实际网络环境规划
  mysql_base-network:
    external: true

services:
  nginx:
    restart: always
    image: nginx
    # command: 
    networks:
      mysql_base-network:
        ipv4_address: 172.16.10.11
    ports:
      - "80:80"
    volumes:
      - ${dist_dir}:/usr/share/nginx/html
      - ${default_config}:/etc/nginx/conf.d/default.conf
