version: '3'
networks:
  keeper:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.16.11.0/24"  # 需根据实际网络环境规划
services:
  etcdkeeper:
    restart: always
    image: konomo/etcdkeeper:v1
    environment:
      - ETCDKEEPER_USETLS=true
      - ETCDKEEPER_CACERT=etcd-ca.pem 
      - ETCDKEEPER_CERT=kube-etcd-healthcheck-client.pem
      - ETCDKEEPER_KEY=kube-etcd-healthcheck-client-key.pem
      - ETCDKEEPER_PORT=8080
    container_name: etcdkeeper
    ports:
      - "8080:8080"
    volumes:
      - ${etcd_pki_dir}:/root/pki  # 如果 TLS 则配置。 
      - /etc/localtime:/etc/localtime:ro
    networks:
      - keeper
    entrypoint:
      - /root/entrypoint.sh
