version: '3'
networks:
  base-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.11.0/24"  # 需根据实际网络环境规划

services:
  mysql:
    restart: always
    image: mysql:5.7.43 # 8.0.0 8.1.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      base-network:
        ipv4_address: 172.16.11.8
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${mysql_data_dir}:/var/lib/mysql
